apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
  annotations:
    konghq.com/plugins: filelogkong
spec:
  ports:
    - port: 8090
      name: high
      protocol: TCP
      targetPort: 8080
    - port: 80
      name: low
      protocol: TCP
      targetPort: 8080
  selector:
    app: echo
